### PR TITLE
Update conda-forge recipe to Neo 0.8.0

### PR DESCRIPTION
**Pull request by jpgill86**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #15. This PR is intended to replace conda-forge/python-neo-feedstock#15 by also including other necessary adjustments to the recipe.

Regarding the update to the dependencies, see also NeuralEnsemble/python-neo#769.

### CODE REVIEW

**Comment by jpgill86** [comment]
@conda-forge-admin, please rerender

**Comment by jpgill86** [comment]
> 
> 
> Hi! This is the friendly automated conda-forge-webservice.
> 
> I tried to re-render for you but ran into some issues, please ping conda-forge/core for further assistance.

@conda-forge/core, the linter ran into an issue when rerendering this recipe. Can I get some help? (This happened a couple hours ago for me in an [unrelated feedstock](https://github.com/conda-forge/libtiff-feedstock/pull/45#issuecomment-554487558)...)

**Comment by jpgill86** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> @conda-forge/core, the linter ran into an issue when rerendering this recipe. Can I get some help? (This happened a couple hours ago for me in an [unrelated feedstock](https://github.com/conda-forge/libtiff-feedstock/pull/45#issuecomment-554487558)...)

When that happens you can try to re-render locally. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally

**Comment by jpgill86** [comment]
> When that happens you can try to re-render locally. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally

I was just working on that, haha. I'm pretty new to conda-forge but am starting to pick it up. You beat me to the local rerender by a couple minutes. 😜

**Comment by ocefpaf** [comment]
> > When that happens you can try to re-render locally. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally
> 
> I was just working on that, haha. I'm pretty new to conda-forge but am starting to pick it up. You beat me to the local rerender by a couple minutes.

BTW, that error message could use the link I sent you. Do you want to send a PR to our webservice adding that?

**Comment by jpgill86** [comment]
> BTW, that error message could use the link I sent you. Do you want to send a PR to our webservice adding that?

That's the way to delegate, haha. Sure, I can do that, but I'm not sure where the webservice is pulling that message from. Can you point me in the right direction?

**Comment by ocefpaf** [comment]
> Can you point me in the right direction?

Sure. I believe it is here:

https://github.com/conda-forge/conda-forge-webservices/blob/a80869b9f2dbc8b5e03d5ae683cdcfc334551f16/conda_forge_webservices/commands.py#L132

**Pull request merged**
