### PR TITLE
Add maintainer zm711

### PR DESCRIPTION
**Pull request by zm711**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zm711** [comment]
Let me know if you want me to actually edit the checklist for this. @jakirkham

**Comment by jakirkham** [comment]
Please only add your username here

https://github.com/conda-forge/python-neo-feedstock/blob/c55d04d90c5ef218fbb1cd2b8612afa7497d87e1/recipe/meta.yaml#L50-L54

Other files are updated automatically

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Thanks Zach! 🙏

**Comment by zm711** [comment]
Thanks for your help @jakirkham!

**Comment by jakirkham** [comment]
Happy to help!

Please follow the next steps in this comment: https://github.com/conda-forge/python-neo-feedstock/commit/012e77b10fae260d44e560c718a755d238bb5b44#commitcomment-138432933

**Pull request merged**
